### ISSUE TITLE
Update\Download error

### ISSUE THREAD

**Issue by MurkBRA** [elundmark/tz-aio-userscript#17] opened 2015-05-04 20:52 UTC
Can't update or download need update this spectrum urls
here is:
// @require       https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.3.3/spectrum.js
// @resource css1 https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.3.3/spectrum.css

![fe317f7beb](https://cloud.githubusercontent.com/assets/12011370/7462230/56493a26-f286-11e4-85d5-52489881de0d.png)

**Comment by MurkBRA** [comment] 2015-05-04 21:02
With this last update 2.9.2 if enable it breaks all others scripts

**Comment by elundmark** [comment] 2015-05-04 21:09
I've tested all the urls needed from my end. They all work ok :-/
I'm pretty sure it's just some temporary downtime, try it again in a minute.
But please explain what you ment by "_ if enable it breaks all others scripts_"?
I understand it might not work as long as the scripts can't be fetched those locations, but does it break other scripts too?

**Comment by MurkBRA** [comment] 2015-05-04 21:20
Seens the script "Torrentz All-in-One Proxy Fix" work on all pages that I open if that page have a userscript it stops working.

**Comment by elundmark** [comment] 2015-05-04 22:41
I found and fixed a bug in the proxy version, I think you'll get it working again now :-)
http://elundmark.se/_files/js/tz-aio/tz-aio.proxy-fix.user.js

~~If you're using the proxy-fix version, make sure you have the newest version; I think the urls you're mentioning aren't the ones in v2.9.2. If you can, compare the one you have installed with [the current one](http://elundmark.se/_files/js/tz-aio/tz-aio.proxy-fix.user.js#BYPASS=TRUE) - or simply uninstall it and re-install again.

Other than that I don't know if I can help you... what userscript engine are you using? GreaseMonkey? And are you using the proxy-fix?

I could try and replicate the error, if you let me know exactly what scripts, browser, and engine you are using. But it sounds to me that the "fault" lies with something else. If it **is** `jsdelivr.net` that's causing the problem, give it another 24h and try it again. I'll keep an eye on it too, and come back to this issue later on.~~

thanks!

**Comment by elundmark** [comment] 2015-05-04 22:45
http://www.websitedown.info/https:cdn.jsdelivr.net

That will check for a domain literaly called "http://https:jsdelivr.net" - I checked it again and it should work. Hopefully the fix I just released was the culprit all along :-)

**Comment by MurkBRA** [comment] 2015-05-05 02:43
[See this here](https://sslcheck.globalsign.com/en_US/sslcheck?host=cdn.jsdelivr.net#94.31.29.138)
this cdn.jsdelivr.net Server has not enabled HTTP Strict-Transport-Security (HTTPS)
you can simple to this:
https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.3.3/spectrum.js
https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.3.3/spectrum.css

About others userscripts work fine now.

**Comment by MurkBRA** [comment] 2015-05-05 03:35
I did this search [here](https://torrentz.eu/search?q=queens+of+the+stone+age)
the alternative search button that show here:
![2aa9a474ce](https://cloud.githubusercontent.com/assets/12011370/7466670/2b66156c-f2be-11e4-9f5c-b4b548ab0319.png)
show link like this:
`data:text/html,<html><meta%20http-equiv="refresh"%20content="0;%20url=http%3A%2F%2Fwww.imdb.com%2Ffind%3Fs%3Dall%26q%3Dqueens%2520of%2520the%2520stone%2520age"><body><a%20href="http://www.imdb.com/find?s=all&q=queens%20of%20the%20stone%20age">http://www.imdb.com/find?s=all&q=queens%20of%20the%20stone%20age</a></body></html>`

**Comment by elundmark** [comment] 2015-05-05 05:19
Ok, I'm pretty sure I know what the problem is now.

**If** the problem lies in the `https:` protocol @ `cdn.jsdelivr.net` - my guess is this:

* Some setting in your browser (either within the browser itself or the userscript engine) has stricter guidelines and rules about `https:` and must be causing the errors; I've tested a fresh install of the latest Firefox + GreaseMonkey **&** Chromium (aka Chrome) + TamperMonkey, with a fresh install of TzAio from Github, and I'm not seing any errors. So...
  1. Either you have an extension or addon installed in your browser that makes it more strict, in which case you should try disabling all your extensions, and only try the userscript engine.
  2. If that doesn't work, try looking in the settings of the userscript.
  3. Do what I did when testing and make a fresh profile and install and test this again.

The reason I can't change the urls to `http:` instead of `https:` is that the sites that host this script **demands** all required scripts to be loaded with `https:`.

If I'm right, you should be able to fix this problem yourself by doing this:
  * Remove the `// @require       https://cdn.jsdelivr.net/jquery.spectrum/1.3.3/spectrum.js` rule, and paste the raw code of that file inside the main script (`tzaio.proxy-fix.user.js`), above the main code. 
  * Then edit the `// @resource css1 https://cdn.jsdelivr.net/jquery.spectrum/1.3.3/spectrum.css` rule for the css to `http:` - resources aren't required to be secure since it's just a stylesheet.

The file is too big already for me to make this change, especially since I'm not yet 100% sure where the problem lies. But I'll try finding the issue again today with another computer, I'll let you knwo how that went. Later!

**Comment by MurkBRA** [comment] 2015-05-05 07:15
I already fix it since my first post with this:
Original:  https://cdn.jsdelivr.net/jquery.spectrum/1.3.3/spectrum.js
Fixed: https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.3.3/spectrum.js

Original:  https://cdn.jsdelivr.net/jquery.spectrum/1.3.3/spectrum.css
Fixed: https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.3.3/spectrum.css

Now I'm just asking you to change too, that is all. Like me I think alot people can't update too. ^^

I'm on greasemonkey and firefox.

**Comment by elundmark** [comment] 2015-05-05 10:49
Oh, sorry :-)

When I first added spectrum, it wasn't available on any other cdn's I could find than jsdelivr ... awesome!
I just have to make sure it works when I upload it to greasemonkey, openuserjs and monkeyguts, they blacklist/whitelist cdn's and change them pretty often... after that I'll change it permanently.

Well, well done!
Sorry if I seamed pig-headed, one of those days I guss :-)

**Comment by elundmark** [comment] 2015-05-05 11:00
Ok, update should be commited soon, I'll close this issue. Many thanks for sticking to it!

**Closed by elundmark** 2015-05-05 11:00 UTC
